version: 1
formatters:
  simple:
    format: '[%(asctime)s] - %(message)s'
    datefmt: '%d/%m %H:%M'
handlers:
  file:
    class: logging.FileHandler
    formatter: simple
    filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
root:
  level: INFO
  handlers: [file]

disable_existing_loggers: false
